pipeline:
  format-and-lint:
    image: python:3.12-slim
    commands:
      - apt-get update -y
      - apt-get install -y build-essential make
      - make install
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - make strip_notebooks
      - make upgrade
      - make format
      - make lint
    when:
      status: [ success ]