when:
  event: [push, pull_request, manual]
  branch: [main, development]

depends_on:
  - test

steps:
  format-and-lint:
    image: python:3.12-slim
    commands:
      - apt-get update -y
      - apt-get install -y build-essential make
      - make install
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - make strip_notebooks
      - make upgrade
      - make format
      - make lint

  push-if-changes:
    image: alpine/git:latest
    commands:
      - git config --global user.name "${CI_COMMIT_AUTHOR}"
      - git config --global user.email "${CI_COMMIT_AUTHOR_EMAIL}"
      - git remote set-url origin "https://oauth2:$${git_push_token}@github.com/${CI_REPO}.git"
      - git add --all
      - |
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "[CI skip] Autocommit, upgrade & format"
          echo "Pushing changes..."
          git push origin ${CI_COMMIT_BRANCH}
        else
          echo "No changes to commit"
        fi
    secrets: [ git_push_token ]