steps:
  format-and-lint:
    image: python:3.12-slim
    commands:
      - apt-get update -y
      - apt-get install -y build-essential make
      - make install
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - make strip_notebooks
      - make upgrade
      - make format
      - make lint
      - |
        if [ -n "$(git status --porcelain)" ]; then
          echo "HAS_CHANGES=true" >> $WOODPECKER_ENV
        else
          echo "HAS_CHANGES=false" >> $WOODPECKER_ENV
        fi