matrix:
  PYTHON_VERSION:
    - "3,7"
    - "3.8"
    - "3.9"
    - "3.10"
    - "3.11"

steps:
  test:
    image: python:${PYTHON_VERSION}
    commands:
      - make dev-install
      - make format lint test