name: commit-changes

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
        description: 'The branch or ref to checkout'

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: make dev-install
      
      - name: Format and upgrade
        run: |
          make format
          make upgrade
      
      - name: Commit and push changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add -A
            git commit -m "style: format code with black and isort"
            git push
          fi