name: Test package

on:
  workflow_call:
    inputs:
      python-versions:
        required: true
        type: string
        description: 'JSON array of Python versions to test against'
      os:
        required: false
        type: string
        default: '["ubuntu-latest", "macos-latest", "windows-latest"]'
        description: 'JSON array of operating systems to test on'

jobs:
  test:
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}
        os: ${{ fromJSON(inputs.os) }}
        exclude:
          # macOS arm64 only supports Python 3.9+
          - os: macos-latest
            python-version: "3.7"
          - os: macos-latest
            python-version: "3.8"
      fail-fast: false
    
    runs-on: ${{ matrix.os }}  # This line was missing
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Install make on Windows
      - name: Install make (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          choco install make
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          Update-SessionEnvironment
      
      # Install make on macOS if not present
      - name: Install make (macOS)
        if: runner.os == 'macOS'
        run: |
          if ! command -v make &> /dev/null; then
            brew install make
          fi
          
      - name: Install dependencies
        run: make dev-install
        
      - name: Lint
        run: make format lint
        
      - name: Test
        run: make test
