name: Test package

on:
  workflow_call:
    inputs:
      python-versions:
        required: true
        type: string
        description: 'JSON array of Python versions to test against'
      os:
        required: false
        type: string
        default: '["ubuntu-latest"]'
        description: 'JSON array of operating systems to test on'

jobs:
  test:
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}
        os: ${{ fromJSON(inputs.os) }}
      fail-fast: false
    
    runs-on: ${{ matrix.os }}  # This line was missing
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: make dev-install
        
      - name: Lint
        run: make format lint
        
      - name: Test
        run: make test
